language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install coverage coveralls flake8 flask-wtf

# command to run tests
script: 
  - coverage run --source=flask_ckeditor setup.py test
  - flake8 flask_ckeditor test_flask_ckeditor.py

after_success: coveralls
